// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'fbd2995f4d9662d65e2c4f1a5657aff1786aeb0a3ed76cd28e83e19039e0bb7a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Bookings: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly fieldId: CodecTypes['pg/uuid@1']['output'];
      readonly bookingDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly totalPrice: CodecTypes['pg/int4@1']['output'];
      readonly status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED';
      readonly paymentStatus: 'UNPAID' | 'PAID' | 'FAILED' | 'REFUNDED' | 'EXPIRED';
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly durationHours: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly BookingTimeSlots: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly bookingId: CodecTypes['pg/uuid@1']['output'];
      readonly startTime: CodecTypes['pg/time-temporal@1']['output'];
      readonly endTime: CodecTypes['pg/time-temporal@1']['output'];
      readonly price: CodecTypes['pg/int4@1']['output'];
      readonly fieldId: CodecTypes['pg/uuid@1']['output'];
      readonly bookingDate: CodecTypes['pg/date-temporal@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly FieldImages: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly fieldId: CodecTypes['pg/uuid@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly FieldOperatingHours: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly fieldId: CodecTypes['pg/uuid@1']['output'];
      readonly dayOfWeek: CodecTypes['pg/int4@1']['output'];
      readonly openTime: CodecTypes['pg/time-temporal@1']['output'];
      readonly closeTime: CodecTypes['pg/time-temporal@1']['output'];
    };
    readonly Fields: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<100>;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly pricePerHour: CodecTypes['pg/int4@1']['output'];
      readonly imageUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly slug: Varchar<120>;
      readonly location: CodecTypes['pg/text@1']['output'] | null;
      readonly _type: Varchar<50> | null;
      readonly capacity: CodecTypes['pg/int4@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Transactions: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly bookingId: CodecTypes['pg/uuid@1']['output'];
      readonly orderId: Varchar<255>;
      readonly grossAmount: CodecTypes['pg/int4@1']['output'];
      readonly paymentMethod:
        'QRIS' | 'BANK_TRANSFER' | 'E_WALLET' | 'CREDIT_CARD' | 'VA' | 'CASH' | null;
      readonly transactionStatus: 'PENDING' | 'SETTLEMENT' | 'EXPIRE' | 'CANCEL' | 'DENY';
      readonly snapToken: CodecTypes['pg/text@1']['output'] | null;
      readonly paidAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly provider: 'MIDTRANS' | 'XENDIT' | 'MANUAL';
      readonly paymentUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly expiredAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Users: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<100>;
      readonly email: Varchar<255>;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'USER';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly phone: Varchar<20> | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Bookings: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly fieldId: CodecTypes['pg/uuid@1']['input'];
      readonly bookingDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly totalPrice: CodecTypes['pg/int4@1']['input'];
      readonly status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED';
      readonly paymentStatus: 'UNPAID' | 'PAID' | 'FAILED' | 'REFUNDED' | 'EXPIRED';
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly durationHours: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly BookingTimeSlots: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly bookingId: CodecTypes['pg/uuid@1']['input'];
      readonly startTime: CodecTypes['pg/time-temporal@1']['input'];
      readonly endTime: CodecTypes['pg/time-temporal@1']['input'];
      readonly price: CodecTypes['pg/int4@1']['input'];
      readonly fieldId: CodecTypes['pg/uuid@1']['input'];
      readonly bookingDate: CodecTypes['pg/date-temporal@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly FieldImages: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly fieldId: CodecTypes['pg/uuid@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly FieldOperatingHours: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly fieldId: CodecTypes['pg/uuid@1']['input'];
      readonly dayOfWeek: CodecTypes['pg/int4@1']['input'];
      readonly openTime: CodecTypes['pg/time-temporal@1']['input'];
      readonly closeTime: CodecTypes['pg/time-temporal@1']['input'];
    };
    readonly Fields: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly pricePerHour: CodecTypes['pg/int4@1']['input'];
      readonly imageUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly slug: CodecTypes['sql/varchar@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'] | null;
      readonly _type: CodecTypes['sql/varchar@1']['input'] | null;
      readonly capacity: CodecTypes['pg/int4@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Transactions: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly bookingId: CodecTypes['pg/uuid@1']['input'];
      readonly orderId: CodecTypes['sql/varchar@1']['input'];
      readonly grossAmount: CodecTypes['pg/int4@1']['input'];
      readonly paymentMethod:
        'QRIS' | 'BANK_TRANSFER' | 'E_WALLET' | 'CREDIT_CARD' | 'VA' | 'CASH' | null;
      readonly transactionStatus: 'PENDING' | 'SETTLEMENT' | 'EXPIRE' | 'CANCEL' | 'DENY';
      readonly snapToken: CodecTypes['pg/text@1']['input'] | null;
      readonly paidAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly provider: 'MIDTRANS' | 'XENDIT' | 'MANUAL';
      readonly paymentUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly expiredAt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Users: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'USER';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly phone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly booking_time_slots: {
      readonly booking_date: CodecTypes['pg/date-temporal@1']['output'];
      readonly booking_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly end_time: CodecTypes['pg/time-temporal@1']['output'];
      readonly field_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly price: CodecTypes['pg/int4@1']['output'];
      readonly start_time: CodecTypes['pg/time-temporal@1']['output'];
    };
    readonly bookings: {
      readonly booking_date: CodecTypes['pg/date-temporal@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly duration_hours: CodecTypes['pg/int4@1']['output'];
      readonly field_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly notes: CodecTypes['pg/text@1']['output'] | null;
      readonly payment_status: 'UNPAID' | 'PAID' | 'FAILED' | 'REFUNDED' | 'EXPIRED';
      readonly status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED';
      readonly total_price: CodecTypes['pg/int4@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly field_images: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly field_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly image_url: CodecTypes['pg/text@1']['output'];
    };
    readonly field_operating_hours: {
      readonly close_time: CodecTypes['pg/time-temporal@1']['output'];
      readonly day_of_week: CodecTypes['pg/int4@1']['output'];
      readonly field_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly open_time: CodecTypes['pg/time-temporal@1']['output'];
    };
    readonly fields: {
      readonly capacity: CodecTypes['pg/int4@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly image_url: CodecTypes['pg/text@1']['output'] | null;
      readonly is_active: CodecTypes['pg/bool@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'] | null;
      readonly name: Varchar<100>;
      readonly price_per_hour: CodecTypes['pg/int4@1']['output'];
      readonly slug: Varchar<120>;
      readonly type: Varchar<50> | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly transactions: {
      readonly booking_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly expired_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly gross_amount: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly order_id: Varchar<255>;
      readonly paid_at: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly payment_method:
        'QRIS' | 'BANK_TRANSFER' | 'E_WALLET' | 'CREDIT_CARD' | 'VA' | 'CASH' | null;
      readonly payment_url: CodecTypes['pg/text@1']['output'] | null;
      readonly provider: 'MIDTRANS' | 'XENDIT' | 'MANUAL';
      readonly snap_token: CodecTypes['pg/text@1']['output'] | null;
      readonly transaction_status: 'PENDING' | 'SETTLEMENT' | 'EXPIRE' | 'CANCEL' | 'DENY';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<255>;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<100>;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly phone: Varchar<20> | null;
      readonly role: 'ADMIN' | 'USER';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly booking_time_slots: {
      readonly booking_date: CodecTypes['pg/date-temporal@1']['input'];
      readonly booking_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly end_time: CodecTypes['pg/time-temporal@1']['input'];
      readonly field_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly price: CodecTypes['pg/int4@1']['input'];
      readonly start_time: CodecTypes['pg/time-temporal@1']['input'];
    };
    readonly bookings: {
      readonly booking_date: CodecTypes['pg/date-temporal@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly duration_hours: CodecTypes['pg/int4@1']['input'];
      readonly field_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly notes: CodecTypes['pg/text@1']['input'] | null;
      readonly payment_status: 'UNPAID' | 'PAID' | 'FAILED' | 'REFUNDED' | 'EXPIRED';
      readonly status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED';
      readonly total_price: CodecTypes['pg/int4@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly field_images: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly field_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly image_url: CodecTypes['pg/text@1']['input'];
    };
    readonly field_operating_hours: {
      readonly close_time: CodecTypes['pg/time-temporal@1']['input'];
      readonly day_of_week: CodecTypes['pg/int4@1']['input'];
      readonly field_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly open_time: CodecTypes['pg/time-temporal@1']['input'];
    };
    readonly fields: {
      readonly capacity: CodecTypes['pg/int4@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly image_url: CodecTypes['pg/text@1']['input'] | null;
      readonly is_active: CodecTypes['pg/bool@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly price_per_hour: CodecTypes['pg/int4@1']['input'];
      readonly slug: CodecTypes['sql/varchar@1']['input'];
      readonly type: CodecTypes['sql/varchar@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly transactions: {
      readonly booking_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly expired_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly gross_amount: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly order_id: CodecTypes['sql/varchar@1']['input'];
      readonly paid_at: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly payment_method:
        'QRIS' | 'BANK_TRANSFER' | 'E_WALLET' | 'CREDIT_CARD' | 'VA' | 'CASH' | null;
      readonly payment_url: CodecTypes['pg/text@1']['input'] | null;
      readonly provider: 'MIDTRANS' | 'XENDIT' | 'MANUAL';
      readonly snap_token: CodecTypes['pg/text@1']['input'] | null;
      readonly transaction_status: 'PENDING' | 'SETTLEMENT' | 'EXPIRE' | 'CANCEL' | 'DENY';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly users: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly phone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly role: 'ADMIN' | 'USER';
      readonly updated_at: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Fields = {
    id: CodecTypes['pg/uuid@1']['output'];
    name: Varchar<100>;
    description: CodecTypes['pg/text@1']['output'] | null;
    pricePerHour: CodecTypes['pg/int4@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'] | null;
    isActive: CodecTypes['pg/bool@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    slug: Varchar<120>;
    location: CodecTypes['pg/text@1']['output'] | null;
    _type: Varchar<50> | null;
    capacity: CodecTypes['pg/int4@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    bookingTimeSlots: public_BookingTimeSlots[];
    bookings: public_Bookings[];
    fieldImages: public_FieldImages[];
    fieldOperatingHours: public_FieldOperatingHours[];
    readonly [RelationKeys]?:
      'bookingTimeSlots' | 'bookings' | 'fieldImages' | 'fieldOperatingHours';
  };
  export type public_Users = {
    id: CodecTypes['pg/uuid@1']['output'];
    name: Varchar<100>;
    email: Varchar<255>;
    password: CodecTypes['pg/text@1']['output'];
    role: 'ADMIN' | 'USER';
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    phone: Varchar<20> | null;
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    bookings: public_Bookings[];
    readonly [RelationKeys]?: 'bookings';
  };
  export type public_Bookings = {
    id: CodecTypes['pg/uuid@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    fieldId: CodecTypes['pg/uuid@1']['output'];
    bookingDate: CodecTypes['pg/date-temporal@1']['output'];
    totalPrice: CodecTypes['pg/int4@1']['output'];
    status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'EXPIRED';
    paymentStatus: 'UNPAID' | 'PAID' | 'FAILED' | 'REFUNDED' | 'EXPIRED';
    notes: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    durationHours: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    bookingTimeSlots: public_BookingTimeSlots[];
    field: public_Fields;
    transactions: public_Transactions[];
    user: public_Users;
    readonly [RelationKeys]?: 'bookingTimeSlots' | 'field' | 'transactions' | 'user';
  };
  export type public_BookingTimeSlots = {
    id: CodecTypes['pg/uuid@1']['output'];
    bookingId: CodecTypes['pg/uuid@1']['output'];
    startTime: CodecTypes['pg/time-temporal@1']['output'];
    endTime: CodecTypes['pg/time-temporal@1']['output'];
    price: CodecTypes['pg/int4@1']['output'];
    fieldId: CodecTypes['pg/uuid@1']['output'];
    bookingDate: CodecTypes['pg/date-temporal@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    booking: public_Bookings;
    field: public_Fields;
    readonly [RelationKeys]?: 'booking' | 'field';
  };
  export type public_FieldImages = {
    id: CodecTypes['pg/uuid@1']['output'];
    fieldId: CodecTypes['pg/uuid@1']['output'];
    imageUrl: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    field: public_Fields;
    readonly [RelationKeys]?: 'field';
  };
  export type public_FieldOperatingHours = {
    id: CodecTypes['pg/uuid@1']['output'];
    fieldId: CodecTypes['pg/uuid@1']['output'];
    dayOfWeek: CodecTypes['pg/int4@1']['output'];
    openTime: CodecTypes['pg/time-temporal@1']['output'];
    closeTime: CodecTypes['pg/time-temporal@1']['output'];
    field: public_Fields;
    readonly [RelationKeys]?: 'field';
  };
  export type public_Transactions = {
    id: CodecTypes['pg/uuid@1']['output'];
    bookingId: CodecTypes['pg/uuid@1']['output'];
    orderId: Varchar<255>;
    grossAmount: CodecTypes['pg/int4@1']['output'];
    paymentMethod: 'QRIS' | 'BANK_TRANSFER' | 'E_WALLET' | 'CREDIT_CARD' | 'VA' | 'CASH' | null;
    transactionStatus: 'PENDING' | 'SETTLEMENT' | 'EXPIRE' | 'CANCEL' | 'DENY';
    snapToken: CodecTypes['pg/text@1']['output'] | null;
    paidAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    provider: 'MIDTRANS' | 'XENDIT' | 'MANUAL';
    paymentUrl: CodecTypes['pg/text@1']['output'] | null;
    expiredAt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamp-temporal@1']['output'];
    booking: public_Bookings;
    readonly [RelationKeys]?: 'booking';
  };
}

export declare const models: {
  public: {
    Fields: Models.public_Fields;
    Users: Models.public_Users;
    Bookings: Models.public_Bookings;
    BookingTimeSlots: Models.public_BookingTimeSlots;
    FieldImages: Models.public_FieldImages;
    FieldOperatingHours: Models.public_FieldOperatingHours;
    Transactions: Models.public_Transactions;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly booking_time_slots: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly booking_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly start_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly end_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly field_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly booking_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'booking_time_slots_pkey';
              };
              uniques: readonly [
                {
                  readonly columns: readonly ['field_id', 'booking_date', 'start_time', 'end_time'];
                  readonly name: 'booking_time_slots_field_id_booking_date_start_time_end_time_un';
                },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking_time_slots';
                    readonly columns: readonly ['booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookings';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'booking_time_slots_booking_id_bookings_id_fk';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking_time_slots';
                    readonly columns: readonly ['field_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fields';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'booking_time_slots_field_id_fields_id_fk';
                },
              ];
            };
            readonly bookings: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly field_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly booking_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly total_price: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'booking_status';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'PENDING'>;
                  };
                  readonly typeParams: { readonly typeName: 'booking_status' };
                };
                readonly payment_status: {
                  readonly nativeType: 'payment_status';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'UNPAID'>;
                  };
                  readonly typeParams: { readonly typeName: 'payment_status' };
                };
                readonly notes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly duration_hours: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'bookings_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookings';
                    readonly columns: readonly ['field_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fields';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'bookings_field_id_fields_id_fk';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookings';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'bookings_user_id_users_id_fk';
                },
              ];
            };
            readonly field_images: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly field_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly image_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'field_images_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'field_images';
                    readonly columns: readonly ['field_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fields';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'field_images_field_id_fields_id_fk';
                },
              ];
            };
            readonly field_operating_hours: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly field_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly day_of_week: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly open_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
                readonly close_time: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'field_operating_hours_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'field_operating_hours';
                    readonly columns: readonly ['field_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fields';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'field_operating_hours_field_id_fields_id_fk';
                },
              ];
            };
            readonly fields: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly price_per_hour: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly image_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly is_active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly slug: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 120 };
                };
                readonly location: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly type: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly capacity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'fields_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['slug']; readonly name: 'fields_slug_unique' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly transactions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly booking_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly order_id: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly gross_amount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly payment_method: {
                  readonly nativeType: 'payment_method';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly typeName: 'payment_method' };
                };
                readonly transaction_status: {
                  readonly nativeType: 'transaction_status';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'PENDING'>;
                  };
                  readonly typeParams: { readonly typeName: 'transaction_status' };
                };
                readonly snap_token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly paid_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly provider: {
                  readonly nativeType: 'payment_provider';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'payment_provider' };
                };
                readonly payment_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly expired_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'transactions_pkey' };
              uniques: readonly [
                {
                  readonly columns: readonly ['order_id'];
                  readonly name: 'transactions_order_id_unique';
                },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'transactions';
                    readonly columns: readonly ['booking_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bookings';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'transactions_booking_id_bookings_id_fk';
                },
              ];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'role';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/enum@1', 'USER'>;
                  };
                  readonly typeParams: { readonly typeName: 'role' };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly phone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'users_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['email']; readonly name: 'users_email_unique' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly BookingStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'CONFIRMED',
                'CANCELLED',
                'COMPLETED',
                'EXPIRED',
              ];
            };
            readonly PaymentMethod: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'QRIS',
                'BANK_TRANSFER',
                'E_WALLET',
                'CREDIT_CARD',
                'VA',
                'CASH',
              ];
            };
            readonly PaymentProvider: {
              readonly kind: 'valueSet';
              readonly values: readonly ['MIDTRANS', 'XENDIT', 'MANUAL'];
            };
            readonly PaymentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['UNPAID', 'PAID', 'FAILED', 'REFUNDED', 'EXPIRED'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'USER'];
            };
            readonly TransactionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'SETTLEMENT', 'EXPIRE', 'CANCEL', 'DENY'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly fields: { readonly namespace: 'public' & NamespaceId; readonly model: 'Fields' };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
    readonly bookings: { readonly namespace: 'public' & NamespaceId; readonly model: 'Bookings' };
    readonly booking_time_slots: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'BookingTimeSlots';
    };
    readonly field_images: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FieldImages';
    };
    readonly field_operating_hours: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FieldOperatingHours';
    };
    readonly transactions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Transactions';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Bookings: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly fieldId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookingDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly totalPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'booking_status' };
                };
              };
              readonly paymentStatus: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'payment_status' };
                };
              };
              readonly notes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly durationHours: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly bookingTimeSlots: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookingTimeSlots';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
              readonly field: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Fields';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fieldId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly transactions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transactions';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'bookings';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly fieldId: { readonly column: 'field_id' };
                readonly bookingDate: { readonly column: 'booking_date' };
                readonly totalPrice: { readonly column: 'total_price' };
                readonly status: { readonly column: 'status' };
                readonly paymentStatus: { readonly column: 'payment_status' };
                readonly notes: { readonly column: 'notes' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly durationHours: { readonly column: 'duration_hours' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly BookingTimeSlots: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly startTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly endTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly fieldId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookingDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Bookings';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly field: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Fields';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fieldId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking_time_slots';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'booking_id' };
                readonly startTime: { readonly column: 'start_time' };
                readonly endTime: { readonly column: 'end_time' };
                readonly price: { readonly column: 'price' };
                readonly fieldId: { readonly column: 'field_id' };
                readonly bookingDate: { readonly column: 'booking_date' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly FieldImages: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly fieldId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly imageUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly field: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Fields';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fieldId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'field_images';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly fieldId: { readonly column: 'field_id' };
                readonly imageUrl: { readonly column: 'image_url' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly FieldOperatingHours: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly fieldId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly dayOfWeek: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly openTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
              readonly closeTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-temporal@1' };
              };
            };
            readonly relations: {
              readonly field: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Fields';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['fieldId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'field_operating_hours';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly fieldId: { readonly column: 'field_id' };
                readonly dayOfWeek: { readonly column: 'day_of_week' };
                readonly openTime: { readonly column: 'open_time' };
                readonly closeTime: { readonly column: 'close_time' };
              };
            };
          };
          readonly Fields: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pricePerHour: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly imageUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 120 };
                };
              };
              readonly location: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly _type: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly capacity: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly bookingTimeSlots: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BookingTimeSlots';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fieldId'];
                };
              };
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Bookings';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fieldId'];
                };
              };
              readonly fieldImages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FieldImages';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fieldId'];
                };
              };
              readonly fieldOperatingHours: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FieldOperatingHours';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fieldId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'fields';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly description: { readonly column: 'description' };
                readonly pricePerHour: { readonly column: 'price_per_hour' };
                readonly imageUrl: { readonly column: 'image_url' };
                readonly isActive: { readonly column: 'is_active' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly slug: { readonly column: 'slug' };
                readonly location: { readonly column: 'location' };
                readonly _type: { readonly column: 'type' };
                readonly capacity: { readonly column: 'capacity' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Transactions: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly grossAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly paymentMethod: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'payment_method' };
                };
              };
              readonly transactionStatus: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'transaction_status' };
                };
              };
              readonly snapToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paidAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'payment_provider' };
                };
              };
              readonly paymentUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiredAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Bookings';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'transactions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'booking_id' };
                readonly orderId: { readonly column: 'order_id' };
                readonly grossAmount: { readonly column: 'gross_amount' };
                readonly paymentMethod: { readonly column: 'payment_method' };
                readonly transactionStatus: { readonly column: 'transaction_status' };
                readonly snapToken: { readonly column: 'snap_token' };
                readonly paidAt: { readonly column: 'paid_at' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly provider: { readonly column: 'provider' };
                readonly paymentUrl: { readonly column: 'payment_url' };
                readonly expiredAt: { readonly column: 'expired_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'role' };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Bookings';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly role: { readonly column: 'role' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly phone: { readonly column: 'phone' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
